# Connecting to the Database

In [2]:
import sqlalchemy
from sqlalchemy import create_engine

# Postgres username, password, and database name
POSTGRES_ADDRESS = 'localhost'
POSTGRES_PORT = '5432'
POSTGRES_USERNAME = 'officems_user'
POSTGRES_PASSWORD = 'secret'
POSTGRES_DBNAME = 'officems_test'
# A long string that contains the necessary Postgres login information
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'.format(username=POSTGRES_USERNAME, password=POSTGRES_PASSWORD, ipaddress=POSTGRES_ADDRESS, port=POSTGRES_PORT, dbname=POSTGRES_DBNAME))
# Create the connection
cnx = create_engine(postgres_str)

# with cnx.connect() as conn:
conn = cnx.raw_connection()
try:
    cursor = conn.cursor()
    cursor.execute("select version()")

    # Fetch a single row using fetchone() method.
    data = cursor.fetchone()
    print("Connection established to: ",data)
    #Retrieving data
    cursor.execute('''SELECT id, parent_id, name_en from DEPARTMENT''')

    #Fetching 1st row from the table
    result = cursor.fetchall();
    #closing the connection
    conn.close()
finally:
    conn.close()


# db_name = 'officems_test'
# user_name = 'officems_user'
# password = 'secret'

# #establishing the connection
# conn = psycopg2.connect(
#    database=db_name, user=user_name, password=password, host='127.0.0.1', port= '5432'
# )
#Creating a cursor object using the cursor() method


#Executing an MYSQL function using the execute() method
# cursor.execute("select version()")

# # Fetch a single row using fetchone() method.
# data = cursor.fetchone()
# print("Connection established to: ",data)

# #Retrieving data
# cursor.execute('''SELECT id, parent_id, name_en from DEPARTMENT''')

# #Fetching 1st row from the table
# result = cursor.fetchall();
# #closing the connection
# conn.close()

Connection established to:  ('PostgreSQL 12.6, compiled by Visual C++ build 1914, 64-bit',)

# Converting the Results to Pandas DataFrame

In [3]:
import pandas as pd
import numpy as np

df = pd.DataFrame(result, columns = ["id", "parent_id", "name"])
df['parent_id'] = df['parent_id'].notnull().astype('int')
# df

# Generating the Closure Table

In [4]:
# key = df[df['id'] == 1]['parent_id']
# type(key)

In [5]:
# key = df[df['id'] == 1]['parent_id']
# print(key)

In [6]:
nodes = []
j = 0
for i, record in df.iterrows():
    descending = int(record.id)
    ascending = int(record.parent_id)
    depth = 0
    j = j+1
    nodes.append((j, descending, descending, depth))
    
    while(ascending != 0):
        j = j+1
        depth = depth+1
        nodes.append((j, descending, ascending, depth))
        ascending = int(df[df['id'] == ascending]['parent_id'])

In [7]:
print(nodes)

[(1, 1, 1, 0), (2, 2, 2, 0), (3, 2, 1, 1), (4, 22, 22, 0), (5, 22, 1, 1), (6, 23, 23, 0), (7, 23, 1, 1), (8, 26, 26, 0), (9, 26, 1, 1), (10, 27, 27, 0), (11, 27, 1, 1), (12, 28, 28, 0), (13, 28, 1, 1), (14, 31, 31, 0), (15, 31, 1, 1), (16, 24, 24, 0), (17, 24, 1, 1), (18, 29, 29, 0), (19, 29, 1, 1), (20, 32, 32, 0), (21, 32, 1, 1), (22, 25, 25, 0), (23, 25, 1, 1), (24, 30, 30, 0), (25, 30, 1, 1), (26, 3, 3, 0), (27, 3, 1, 1), (28, 4, 4, 0), (29, 4, 1, 1), (30, 5, 5, 0), (31, 5, 1, 1), (32, 9, 9, 0), (33, 9, 1, 1), (34, 55, 55, 0), (35, 55, 1, 1), (36, 56, 56, 0), (37, 56, 1, 1), (38, 60, 60, 0), (39, 60, 1, 1), (40, 68, 68, 0), (41, 68, 1, 1), (42, 69, 69, 0), (43, 69, 1, 1), (44, 57, 57, 0), (45, 57, 1, 1), (46, 61, 61, 0), (47, 61, 1, 1), (48, 62, 62, 0), (49, 62, 1, 1), (50, 63, 63, 0), (51, 63, 1, 1), (52, 64, 64, 0), (53, 64, 1, 1), (54, 65, 65, 0), (55, 65, 1, 1), (56, 58, 58, 0), (57, 58, 1, 1), (58, 66, 66, 0), (59, 66, 1, 1), (60, 70, 70, 0), (61, 70, 1, 1), (62, 67, 67, 0), (63, 67, 1, 1), (64, 71, 71, 0), (65, 71, 1, 1), (66, 72, 72, 0), (67, 72, 1, 1), (68, 59, 59, 0), (69, 59, 1, 1), (70, 10, 10, 0), (71, 10, 1, 1), (72, 73, 73, 0), (73, 73, 1, 1), (74, 75, 75, 0), (75, 75, 1, 1), (76, 83, 83, 0), (77, 83, 1, 1), (78, 86, 86, 0), (79, 86, 1, 1), (80, 103, 103, 0), (81, 103, 1, 1), (82, 84, 84, 0), (83, 84, 1, 1), (84, 87, 87, 0), (85, 87, 1, 1), (86, 104, 104, 0), (87, 104, 1, 1), (88, 85, 85, 0), (89, 85, 1, 1), (90, 88, 88, 0), (91, 88, 1, 1), (92, 105, 105, 0), (93, 105, 1, 1), (94, 74, 74, 0), (95, 74, 1, 1), (96, 76, 76, 0), (97, 76, 1, 1), (98, 89, 89, 0), (99, 89, 1, 1), (100, 106, 106, 0), (101, 106, 1, 1), (102, 90, 90, 0), (103, 90, 1, 1), (104, 77, 77, 0), (105, 77, 1, 1), (106, 91, 91, 0), (107, 91, 1, 1), (108, 92, 92, 0), (109, 92, 1, 1), (110, 93, 93, 0), (111, 93, 1, 1), (112, 94, 94, 0), (113, 94, 1, 1), (114, 95, 95, 0), (115, 95, 1, 1), (116, 78, 78, 0), (117, 78, 1, 1), (118, 96, 96, 0), (119, 96, 1, 1), (120, 97, 97, 0), (121, 97, 1, 1), (122, 98, 98, 0), (123, 98, 1, 1), (124, 79, 79, 0), (125, 79, 1, 1), (126, 99, 99, 0), (127, 99, 1, 1), (128, 100, 100, 0), (129, 100, 1, 1), (130, 101, 101, 0), (131, 101, 1, 1), (132, 107, 107, 0), (133, 107, 1, 1), (134, 80, 80, 0), (135, 80, 1, 1), (136, 81, 81, 0), (137, 81, 1, 1), (138, 102, 102, 0), (139, 102, 1, 1), (140, 82, 82, 0), (141, 82, 1, 1), (142, 108, 108, 0), (143, 108, 1, 1), (144, 33, 33, 0), (145, 33, 1, 1), (146, 34, 34, 0), (147, 34, 1, 1), (148, 35, 35, 0), (149, 35, 1, 1), (150, 47, 47, 0), (151, 47, 1, 1), (152, 54, 54, 0), (153, 54, 1, 1), (154, 36, 36, 0), (155, 36, 1, 1), (156, 40, 40, 0), (157, 40, 1, 1), (158, 41, 41, 0), (159, 41, 1, 1), (160, 42, 42, 0), (161, 42, 1, 1), (162, 37, 37, 0), (163, 37, 1, 1), (164, 43, 43, 0), (165, 43, 1, 1), (166, 48, 48, 0), (167, 48, 1, 1), (168, 38, 38, 0), (169, 38, 1, 1), (170, 44, 44, 0), (171, 44, 1, 1), (172, 49, 49, 0), (173, 49, 1, 1), (174, 39, 39, 0), (175, 39, 1, 1), (176, 45, 45, 0), (177, 45, 1, 1), (178, 50, 50, 0), (179, 50, 1, 1), (180, 51, 51, 0), (181, 51, 1, 1), (182, 46, 46, 0), (183, 46, 1, 1), (184, 52, 52, 0), (185, 52, 1, 1), (186, 53, 53, 0), (187, 53, 1, 1), (188, 282, 282, 0), (189, 282, 1, 1), (190, 283, 283, 0), (191, 283, 1, 1), (192, 6, 6, 0), (193, 6, 1, 1), (194, 11, 11, 0), (195, 11, 1, 1), (196, 116, 116, 0), (197, 116, 1, 1), (198, 117, 117, 0), (199, 117, 1, 1), (200, 118, 118, 0), (201, 118, 1, 1), (202, 119, 119, 0), (203, 119, 1, 1), (204, 120, 120, 0), (205, 120, 1, 1), (206, 124, 124, 0), (207, 124, 1, 1), (208, 121, 121, 0), (209, 121, 1, 1), (210, 125, 125, 0), (211, 125, 1, 1), (212, 122, 122, 0), (213, 122, 1, 1), (214, 126, 126, 0), (215, 126, 1, 1), (216, 123, 123, 0), (217, 123, 1, 1), (218, 127, 127, 0), (219, 127, 1, 1), (220, 12, 12, 0), (221, 12, 1, 1), (222, 128, 128, 0), (223, 128, 1, 1), (224, 129, 129, 0), (225, 129, 1, 1), (226, 132, 132, 0), (227, 132, 1, 1), (228, 138, 138, 0), (229, 138, 1, 1), (230, 133, 133, 0), (231, 133, 1, 1), (232, 139, 139, 0), (233, 139, 1, 1), (234, 130, 130, 0), (235, 130, 1, 1), (236, 134, 134, 0), (237, 134, 1, 1), (238, 140, 140, 0), (239, 140, 1, 1), (240, 135, 135, 0), (241, 135, 1, 1), (242, 194, 194, 0), (243, 194, 1, 1), (244, 141, 141, 0), (245, 141, 1, 1), (246, 131, 131, 0), (247, 131, 1, 1), (248, 136, 136, 0), (249, 136, 1, 1), (250, 137, 137, 0), (251, 137, 1, 1), (252, 109, 109, 0), (253, 109, 1, 1), (254, 110, 110, 0), (255, 110, 1, 1), (256, 111, 111, 0), (257, 111, 1, 1), (258, 113, 113, 0), (259, 113, 1, 1), (260, 114, 114, 0), (261, 114, 1, 1), (262, 115, 115, 0), (263, 115, 1, 1), (264, 112, 112, 0), (265, 112, 1, 1), (266, 7, 7, 0), (267, 7, 1, 1), (268, 13, 13, 0), (269, 13, 1, 1), (270, 174, 174, 0), (271, 174, 1, 1), (272, 175, 175, 0), (273, 175, 1, 1), (274, 176, 176, 0), (275, 176, 1, 1), (276, 183, 183, 0), (277, 183, 1, 1), (278, 177, 177, 0), (279, 177, 1, 1), (280, 184, 184, 0), (281, 184, 1, 1), (282, 178, 178, 0), (283, 178, 1, 1), (284, 185, 185, 0), (285, 185, 1, 1), (286, 179, 179, 0), (287, 179, 1, 1), (288, 186, 186, 0), (289, 186, 1, 1), (290, 180, 180, 0), (291, 180, 1, 1), (292, 187, 187, 0), (293, 187, 1, 1), (294, 181, 181, 0), (295, 181, 1, 1), (296, 182, 182, 0), (297, 182, 1, 1), (298, 188, 188, 0), (299, 188, 1, 1), (300, 14, 14, 0), (301, 14, 1, 1), (302, 189, 189, 0), (303, 189, 1, 1), (304, 190, 190, 0), (305, 190, 1, 1), (306, 207, 207, 0), (307, 207, 1, 1), (308, 191, 191, 0), (309, 191, 1, 1), (310, 208, 208, 0), (311, 208, 1, 1), (312, 192, 192, 0), (313, 192, 1, 1), (314, 193, 193, 0), (315, 193, 1, 1), (316, 195, 195, 0), (317, 195, 1, 1), (318, 196, 196, 0), (319, 196, 1, 1), (320, 197, 197, 0), (321, 197, 1, 1), (322, 198, 198, 0), (323, 198, 1, 1), (324, 199, 199, 0), (325, 199, 1, 1), (326, 200, 200, 0), (327, 200, 1, 1), (328, 201, 201, 0), (329, 201, 1, 1), (330, 202, 202, 0), (331, 202, 1, 1), (332, 209, 209, 0), (333, 209, 1, 1), (334, 203, 203, 0), (335, 203, 1, 1), (336, 204, 204, 0), (337, 204, 1, 1), (338, 205, 205, 0), (339, 205, 1, 1), (340, 210, 210, 0), (341, 210, 1, 1), (342, 206, 206, 0), (343, 206, 1, 1), (344, 211, 211, 0), (345, 211, 1, 1), (346, 212, 212, 0), (347, 212, 1, 1), (348, 15, 15, 0), (349, 15, 1, 1), (350, 213, 213, 0), (351, 213, 1, 1), (352, 214, 214, 0), (353, 214, 1, 1), (354, 215, 215, 0), (355, 215, 1, 1), (356, 227, 227, 0), (357, 227, 1, 1), (358, 216, 216, 0), (359, 216, 1, 1), (360, 228, 228, 0), (361, 228, 1, 1), (362, 217, 217, 0), (363, 217, 1, 1), (364, 229, 229, 0), (365, 229, 1, 1), (366, 218, 218, 0), (367, 218, 1, 1), (368, 230, 230, 0), (369, 230, 1, 1), (370, 219, 219, 0), (371, 219, 1, 1), (372, 220, 220, 0), (373, 220, 1, 1), (374, 221, 221, 0), (375, 221, 1, 1), (376, 222, 222, 0), (377, 222, 1, 1), (378, 223, 223, 0), (379, 223, 1, 1), (380, 224, 224, 0), (381, 224, 1, 1), (382, 225, 225, 0), (383, 225, 1, 1), (384, 231, 231, 0), (385, 231, 1, 1), (386, 226, 226, 0), (387, 226, 1, 1), (388, 232, 232, 0), (389, 232, 1, 1), (390, 233, 233, 0), (391, 233, 1, 1), (392, 268, 268, 0), (393, 268, 1, 1), (394, 16, 16, 0), (395, 16, 1, 1), (396, 234, 234, 0), (397, 234, 1, 1), (398, 235, 235, 0), (399, 235, 1, 1), (400, 240, 240, 0), (401, 240, 1, 1), (402, 253, 253, 0), (403, 253, 1, 1), (404, 241, 241, 0), (405, 241, 1, 1), (406, 254, 254, 0), (407, 254, 1, 1), (408, 242, 242, 0), (409, 242, 1, 1), (410, 255, 255, 0), (411, 255, 1, 1), (412, 236, 236, 0), (413, 236, 1, 1), (414, 243, 243, 0), (415, 243, 1, 1), (416, 256, 256, 0), (417, 256, 1, 1), (418, 244, 244, 0), (419, 244, 1, 1), (420, 257, 257, 0), (421, 257, 1, 1), (422, 245, 245, 0), (423, 245, 1, 1), (424, 258, 258, 0), (425, 258, 1, 1), (426, 237, 237, 0), (427, 237, 1, 1), (428, 246, 246, 0), (429, 246, 1, 1), (430, 259, 259, 0), (431, 259, 1, 1), (432, 247, 247, 0), (433, 247, 1, 1), (434, 248, 248, 0), (435, 248, 1, 1), (436, 260, 260, 0), (437, 260, 1, 1), (438, 238, 238, 0), (439, 238, 1, 1), (440, 249, 249, 0), (441, 249, 1, 1), (442, 250, 250, 0), (443, 250, 1, 1), (444, 261, 261, 0), (445, 261, 1, 1), (446, 251, 251, 0), (447, 251, 1, 1), (448, 273, 273, 0), (449, 273, 1, 1), (450, 262, 262, 0), (451, 262, 1, 1), (452, 239, 239, 0), (453, 239, 1, 1), (454, 252, 252, 0), (455, 252, 1, 1), (456, 17, 17, 0), (457, 17, 1, 1), (458, 149, 149, 0), (459, 149, 1, 1), (460, 150, 150, 0), (461, 150, 1, 1), (462, 151, 151, 0), (463, 151, 1, 1), (464, 152, 152, 0), (465, 152, 1, 1), (466, 153, 153, 0), (467, 153, 1, 1), (468, 154, 154, 0), (469, 154, 1, 1), (470, 155, 155, 0), (471, 155, 1, 1), (472, 156, 156, 0), (473, 156, 1, 1), (474, 157, 157, 0), (475, 157, 1, 1), (476, 158, 158, 0), (477, 158, 1, 1), (478, 159, 159, 0), (479, 159, 1, 1), (480, 160, 160, 0), (481, 160, 1, 1), (482, 171, 171, 0), (483, 171, 1, 1), (484, 161, 161, 0), (485, 161, 1, 1), (486, 162, 162, 0), (487, 162, 1, 1), (488, 163, 163, 0), (489, 163, 1, 1), (490, 164, 164, 0), (491, 164, 1, 1), (492, 165, 165, 0), (493, 165, 1, 1), (494, 166, 166, 0), (495, 166, 1, 1), (496, 167, 167, 0), (497, 167, 1, 1), (498, 168, 168, 0), (499, 168, 1, 1), (500, 169, 169, 0), (501, 169, 1, 1), (502, 172, 172, 0), (503, 172, 1, 1), (504, 170, 170, 0), (505, 170, 1, 1), (506, 173, 173, 0), (507, 173, 1, 1), (508, 18, 18, 0), (509, 18, 1, 1), (510, 263, 263, 0), (511, 263, 1, 1), (512, 264, 264, 0), (513, 264, 1, 1), (514, 269, 269, 0), (515, 269, 1, 1), (516, 265, 265, 0), (517, 265, 1, 1), (518, 270, 270, 0), (519, 270, 1, 1), (520, 266, 266, 0), (521, 266, 1, 1), (522, 271, 271, 0), (523, 271, 1, 1), (524, 267, 267, 0), (525, 267, 1, 1), (526, 272, 272, 0), (527, 272, 1, 1), (528, 274, 274, 0), (529, 274, 1, 1), (530, 142, 142, 0), (531, 142, 1, 1), (532, 145, 145, 0), (533, 145, 1, 1), (534, 146, 146, 0), (535, 146, 1, 1), (536, 147, 147, 0), (537, 147, 1, 1), (538, 148, 148, 0), (539, 148, 1, 1), (540, 143, 143, 0), (541, 143, 1, 1), (542, 144, 144, 0), (543, 144, 1, 1), (544, 8, 8, 0), (545, 8, 1, 1), (546, 19, 19, 0), (547, 19, 1, 1), (548, 284, 284, 0), (549, 284, 1, 1), (550, 285, 285, 0), (551, 285, 1, 1), (552, 286, 286, 0), (553, 286, 1, 1), (554, 287, 287, 0), (555, 287, 1, 1), (556, 288, 288, 0), (557, 288, 1, 1), (558, 289, 289, 0), (559, 289, 1, 1), (560, 290, 290, 0), (561, 290, 1, 1), (562, 291, 291, 0), (563, 291, 1, 1), (564, 292, 292, 0), (565, 292, 1, 1), (566, 293, 293, 0), (567, 293, 1, 1), (568, 294, 294, 0), (569, 294, 1, 1), (570, 295, 295, 0), (571, 295, 1, 1), (572, 296, 296, 0), (573, 296, 1, 1), (574, 297, 297, 0), (575, 297, 1, 1), (576, 298, 298, 0), (577, 298, 1, 1), (578, 299, 299, 0), (579, 299, 1, 1), (580, 300, 300, 0), (581, 300, 1, 1), (582, 301, 301, 0), (583, 301, 1, 1), (584, 302, 302, 0), (585, 302, 1, 1), (586, 303, 303, 0), (587, 303, 1, 1), (588, 304, 304, 0), (589, 304, 1, 1), (590, 305, 305, 0), (591, 305, 1, 1), (592, 306, 306, 0), (593, 306, 1, 1), (594, 307, 307, 0), (595, 307, 1, 1), (596, 308, 308, 0), (597, 308, 1, 1), (598, 309, 309, 0), (599, 309, 1, 1), (600, 310, 310, 0), (601, 310, 1, 1), (602, 311, 311, 0), (603, 311, 1, 1), (604, 312, 312, 0), (605, 312, 1, 1), (606, 313, 313, 0), (607, 313, 1, 1), (608, 314, 314, 0), (609, 314, 1, 1), (610, 315, 315, 0), (611, 315, 1, 1), (612, 316, 316, 0), (613, 316, 1, 1), (614, 317, 317, 0), (615, 317, 1, 1), (616, 318, 318, 0), (617, 318, 1, 1), (618, 319, 319, 0), (619, 319, 1, 1), (620, 320, 320, 0), (621, 320, 1, 1), (622, 321, 321, 0), (623, 321, 1, 1), (624, 322, 322, 0), (625, 322, 1, 1), (626, 323, 323, 0), (627, 323, 1, 1), (628, 324, 324, 0), (629, 324, 1, 1), (630, 325, 325, 0), (631, 325, 1, 1), (632, 326, 326, 0), (633, 326, 1, 1), (634, 327, 327, 0), (635, 327, 1, 1), (636, 328, 328, 0), (637, 328, 1, 1), (638, 20, 20, 0), (639, 20, 1, 1), (640, 329, 329, 0), (641, 329, 1, 1), (642, 330, 330, 0), (643, 330, 1, 1), (644, 331, 331, 0), (645, 331, 1, 1), (646, 332, 332, 0), (647, 332, 1, 1), (648, 333, 333, 0), (649, 333, 1, 1), (650, 334, 334, 0), (651, 334, 1, 1), (652, 335, 335, 0), (653, 335, 1, 1), (654, 336, 336, 0), (655, 336, 1, 1), (656, 337, 337, 0), (657, 337, 1, 1), (658, 338, 338, 0), (659, 338, 1, 1), (660, 339, 339, 0), (661, 339, 1, 1), (662, 340, 340, 0), (663, 340, 1, 1), (664, 341, 341, 0), (665, 341, 1, 1), (666, 342, 342, 0), (667, 342, 1, 1), (668, 343, 343, 0), (669, 343, 1, 1), (670, 344, 344, 0), (671, 344, 1, 1), (672, 21, 21, 0), (673, 21, 1, 1), (674, 345, 345, 0), (675, 345, 1, 1), (676, 346, 346, 0), (677, 346, 1, 1), (678, 347, 347, 0), (679, 347, 1, 1), (680, 348, 348, 0), (681, 348, 1, 1), (682, 349, 349, 0), (683, 349, 1, 1), (684, 350, 350, 0), (685, 350, 1, 1), (686, 351, 351, 0), (687, 351, 1, 1), (688, 352, 352, 0), (689, 352, 1, 1), (690, 353, 353, 0), (691, 353, 1, 1), (692, 354, 354, 0), (693, 354, 1, 1), (694, 355, 355, 0), (695, 355, 1, 1), (696, 356, 356, 0), (697, 356, 1, 1), (698, 357, 357, 0), (699, 357, 1, 1), (700, 358, 358, 0), (701, 358, 1, 1), (702, 359, 359, 0), (703, 359, 1, 1), (704, 360, 360, 0), (705, 360, 1, 1), (706, 361, 361, 0), (707, 361, 1, 1), (708, 362, 362, 0), (709, 362, 1, 1), (710, 363, 363, 0), (711, 363, 1, 1), (712, 364, 364, 0), (713, 364, 1, 1), (714, 365, 365, 0), (715, 365, 1, 1), (716, 366, 366, 0), (717, 366, 1, 1), (718, 367, 367, 0), (719, 367, 1, 1), (720, 368, 368, 0), (721, 368, 1, 1), (722, 369, 369, 0), (723, 369, 1, 1), (724, 370, 370, 0), (725, 370, 1, 1), (726, 371, 371, 0), (727, 371, 1, 1), (728, 372, 372, 0), (729, 372, 1, 1), (730, 373, 373, 0), (731, 373, 1, 1), (732, 374, 374, 0), (733, 374, 1, 1), (734, 375, 375, 0), (735, 375, 1, 1), (736, 376, 376, 0), (737, 376, 1, 1), (738, 377, 377, 0), (739, 377, 1, 1), (740, 378, 378, 0), (741, 378, 1, 1), (742, 379, 379, 0), (743, 379, 1, 1), (744, 275, 275, 0), (745, 275, 1, 1), (746, 277, 277, 0), (747, 277, 1, 1), (748, 278, 278, 0), (749, 278, 1, 1), (750, 279, 279, 0), (751, 279, 1, 1), (752, 280, 280, 0), (753, 280, 1, 1), (754, 281, 281, 0), (755, 281, 1, 1), (756, 276, 276, 0), (757, 276, 1, 1)]

In [8]:
table = pd.DataFrame(nodes, columns = ['id', 'descendant_id', 'ancestor_id', 'depth'])
table

      id  descendant_id  ancestor_id  depth
0      1              1            1      0
1      2              2            2      0
2      3              2            1      1
3      4             22           22      0
4      5             22            1      1
..   ...            ...          ...    ...
752  753            280            1      1
753  754            281          281      0
754  755            281            1      1
755  756            276          276      0
756  757            276            1      1

[757 rows x 4 columns]

In [9]:
table.to_sql('department_closure', con=cnx, if_exists='append',index=False)
print("successfully saved in db")

successfully saved in db